/**
 * Tokens de inyección para diferentes stores
 * Solución usando Injection Tokens
 */
export const DATA_STORE_TOKENS = {
  USERS: 'USERS_DATA_STORE',
  WALLETS: 'WALLETS_DATA_STORE',
  PRODUCTS: 'PRODUCTS_DATA_STORE',
  ORDERS: 'ORDERS_DATA_STORE',
  GACHA_POOLS: 'GACHA_POOLS_DATA_STORE',
  GACHA_PLAYERS: 'GACHA_PLAYERS_DATA_STORE',
  OWNED_PLAYERS: 'OWNED_PLAYERS_DATA_STORE',
  PENALTY_SESSIONS: 'PENALTY_SESSIONS_DATA_STORE',
  LEDGER: 'LEDGER_DATA_STORE',
  CHALLENGES: 'CHALLENGES_DATA_STORE',
  IDEMPOTENCY: 'IDEMPOTENCY_DATA_STORE',
} as const;