version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: goalplay
      POSTGRES_USER: goalplay
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U goalplay"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=goalplay
      - DB_PASSWORD=password
      - DB_DATABASE=goalplay
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:backend:dev
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: