name: gol-play
services:
  # Backend API Service
  - name: backend
    source_dir: .
    github:
      repo: tu-usuario/gol-play
      branch: main
    run_command: npm run start:backend:prod
    build_command: npm ci && npm run build:backend
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /api
      - path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: DB_TYPE
        value: postgres
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${game-app-db.DATABASE_URL}
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: JWT_SECRET
        value: 6A9p/j03HVp3oHTq4uwDfJ81MRddUajbUfhDGaOUIEc=
      - key: CORS_ORIGIN
        value: https://game.goalplay.pro
      - key: FRONTEND_URL
        value: https://game.goalplay.pro
      - key: BSCSCAN_API_KEY
        value: YourBSCScanApiKeyHere
      - key: BSC_RPC_URL
        value: https://bsc-dataseed1.binance.org/
      - key: ETH_RECEIVING_WALLET_1
        value: 0x742d35Cc6635C0532925a3b8D34C83dD3e0Be000
      - key: BSC_RECEIVING_WALLET_1
        value: 0x742d35Cc6635C0532925a3b8D34C83dD3e0Be000
      - key: POLYGON_RECEIVING_WALLET_1
        value: 0x742d35Cc6635C0532925a3b8D34C83dD3e0Be000
      - key: ARB_RECEIVING_WALLET_1
        value: 0x742d35Cc6635C0532925a3b8D34C83dD3e0Be000
      - key: SOL_RECEIVING_WALLET_1
        value: 11111111111111111111111111111112

  # Frontend Static Site
  - name: frontend
    source_dir: .
    github:
      repo: tu-usuario/gol-play
      branch: main
    build_command: npm ci && npm run build:frontend
    run_command: npm run preview -- --port 3000 --host 0.0.0.0
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        scope: RUN_AND_BUILD_TIME
        value: /api

# Database
databases:
  - name: game-app-db
    engine: PG
    version: "17"
    size: basic
    num_nodes: 1
    db_name: goalplay
    user: goalplay
    trusted_sources:
      - backend
